### PR TITLE
fix: read Mach-O load command string until null terminator

### LINKED ISSUE #2106: [Bug]: PlayCover crashes when installing  洛克王国：世界
### Describe the bug

Hi, I'm trying to install an app into PlayCover, and when it almost finishes, "PlayCover quit unexpectedly". Here is the crash log (Show Details). Please help, many thx!

### Enviroment

<!DOCTYPE html><figure class="md-table-fig table-figure" cid="n2" mdtype="table" style="box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgb(59 130 246 / .5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(0, 122, 255); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">
Field | Value
-- | --
macOS version | Sequoia 15.6.1
Mac model | MacBook pro M4pro
PlayCover version | 3.1.0(nightly)
Game | 洛克王国：世界(CN)

</figure>

### Steps to reproduce

Install 

> com.tencent.nrc_1.100.88_und3fined.ipa

which was downloaded from [https://decrypt.day/app/id6478654994](url)

### Expected behaviour

It will crash when its almost finfished installing.

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               PlayCover [16550]
Path:                  /Applications/PlayCover.app/Contents/MacOS/PlayCover
Identifier:            io.playcover.PlayCover
Version:               3.1.0 (1428)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2026-03-24 19:55:16.6319 +0800
OS Version:            macOS 15.6.1 (24G90)
Report Version:        12
Anonymous UUID:        7615BF27-9E1D-8F2A-5578-3B2FC66F408D

Sleep/Wake UUID:       91AC358C-AC28-4CF1-B291-62562D88D8D7

Time Awake Since Boot: 530000 seconds
Time Since Wake:       926 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000104dbcbd0

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [16550]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18ee61c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18ee743a0 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x18ee6a764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x18ee61fa8 mach_msg + 24
4   CoreFoundation                	       0x18ef8ecbc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18ef8d5d8 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18ef8ca98 CFRunLoopRunSpecific + 572
7   HIToolbox                     	       0x19aa2f27c RunCurrentEventLoopInMode + 324
8   HIToolbox                     	       0x19aa324e8 ReceiveNextEventCommon + 676
9   HIToolbox                     	       0x19abbd484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x192eb1a34 _DPSNextEvent + 684
11  AppKit                        	       0x193850940 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
12  AppKit                        	       0x192ea4be4 -[NSApplication run] + 480
13  AppKit                        	       0x192e7b2dc NSApplicationMain + 880
14  SwiftUI                       	       0x1bed34878 specialized runApp(_:) + 160
15  SwiftUI                       	       0x1bf192658 runApp<A>(_:) + 108
16  SwiftUI                       	       0x1bf4f35c0 static App.main() + 224
17  PlayCover                     	       0x104e310d0 0x104d84000 + 708816
18  dyld                          	       0x18eb02b98 start + 6076

Thread 1 Crashed:
0   PlayCover                     	       0x104dbcbd0 0x104d84000 + 232400
1   PlayCover                     	       0x104dbe5a4 0x104d84000 + 239012
2   PlayCover                     	       0x104dbed88 0x104d84000 + 241032
3   PlayCover                     	       0x104dbf43c 0x104d84000 + 242748
4   PlayCover                     	       0x104dbf76c 0x104d84000 + 243564
5   PlayCover                     	       0x104da01d4 0x104d84000 + 115156
6   PlayCover                     	       0x104d91379 0x104d84000 + 54137
7   PlayCover                     	       0x104db80f1 0x104d84000 + 213233
8   PlayCover                     	       0x104d91379 0x104d84000 + 54137
9   libswift_Concurrency.dylib    	       0x27773e83d completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 2:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x18ee61bb0 semaphore_wait_trap + 8
1   caulk                         	       0x19a516cc8 caulk::semaphore::timed_wait(double) + 224
2   caulk                         	       0x19a516b70 caulk::concurrent::details::worker_thread::run() + 32
3   caulk                         	       0x19a516844 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x18eea3c0c _pthread_start + 136
5   libsystem_pthread.dylib       	       0x18ee9eb80 thread_start + 8

Thread 3:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	       0x18ee61bb0 semaphore_wait_trap + 8
1   caulk                         	       0x19a516cc8 caulk::semaphore::timed_wait(double) + 224
2   caulk                         	       0x19a516b70 caulk::concurrent::details::worker_thread::run() + 32
3   caulk                         	       0x19a516844 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x18eea3c0c _pthread_start + 136
5   libsystem_pthread.dylib       	       0x18ee9eb80 thread_start + 8

Thread 4:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18ee61c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18ee743a0 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x18ee6a764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x18ee61fa8 mach_msg + 24
4   CoreFoundation                	       0x18ef8ecbc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18ef8d5d8 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18ef8ca98 CFRunLoopRunSpecific + 572
7   AppKit                        	       0x192fd578c _NSEventThread + 140
8   libsystem_pthread.dylib       	       0x18eea3c0c _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18ee9eb80 thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 9:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	       0x18ee61c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x18ee743a0 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x18ee6a764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x18ee61fa8 mach_msg + 24
4   CoreFoundation                	       0x18ef8ecbc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18ef8d5d8 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x18ef8ca98 CFRunLoopRunSpecific + 572
7   CFNetwork                     	       0x194c972f4 +[__CFN_CoreSchedulingSetRunnable _run:] + 416
8   Foundation                    	       0x190556ba8 __NSThread__start__ + 732
9   libsystem_pthread.dylib       	       0x18eea3c0c _pthread_start + 136
10  libsystem_pthread.dylib       	       0x18ee9eb80 thread_start + 8

Thread 10:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	       0x18ee9eb6c start_wqthread + 0


Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000600003c5ca08   x1: 0x0000000600000003   x2: 0x000000018eb34e40   x3: 0x00000001fdeabc38
    x4: 0x000000000000000b   x5: 0x0000000090a55056   x6: 0x000060000058d540   x7: 0x0000000000000000
    x8: 0xfffffffe00000000   x9: 0x0000000600000003  x10: 0x0000000400000003  x11: 0x0000000000001540
   x12: 0x00000000000007fb  x13: 0x00000000000007fd  x14: 0x0000000090e55056  x15: 0x0000000090c54857
   x16: 0x00000001a09dacdc  x17: 0x0000000000000238  x18: 0x0000000000000000  x19: 0x00002cf000002cd0
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x4000600003c5ca00  x23: 0x0001000000010000
   x24: 0x0000000000000018  x25: 0x0000000000000002  x26: 0x4000600003c5ca00  x27: 0x00002cf000002cb8
   x28: 0x000000000000000c   fp: 0x000000016b1028e0   lr: 0x0000000104dbcab4
    sp: 0x000000016b102800   pc: 0x0000000104dbcbd0 cpsr: 0x60000000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x104d84000 -        0x104fe3fff io.playcover.PlayCover (3.1.0) <43c12fe4-fbbc-394d-8317-3f10f6513e55> /Applications/PlayCover.app/Contents/MacOS/PlayCover
       0x105180000 -        0x1051d3fff org.sparkle-project.Sparkle (2.9.0) <76717cef-e15b-3086-acee-87e1c8b99d60> /Applications/PlayCover.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x1085cc000 -        0x1085d7fff libobjc-trampolines.dylib (*) <a3faee04-0f8b-3428-9497-560c97eca6fb> /usr/lib/libobjc-trampolines.dylib
       0x10cb8c000 -        0x10d2bffff com.apple.AGXMetalG16X (329.2) <8e5557ce-84f2-3aa0-a631-94d3809e5bf0> /System/Library/Extensions/AGXMetalG16X.bundle/Contents/MacOS/AGXMetalG16X
       0x18ee61000 -        0x18ee9c653 libsystem_kernel.dylib (*) <6e4a96ad-04b8-3e8a-b91d-087e62306246> /usr/lib/system/libsystem_kernel.dylib
       0x18ef12000 -        0x18f450fff com.apple.CoreFoundation (6.9) <8d45baee-6cc0-3b89-93fd-ea1c8e15c6d7> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19a96c000 -        0x19ac72fdf com.apple.HIToolbox (2.1.1) <1a037942-11e0-3fc8-aad2-20b11e7ae1a4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x192e77000 -        0x194307e3f com.apple.AppKit (6.9) <860c164c-d04c-30ff-8c6f-e672b74caf11> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1becec000 -        0x1c041341f com.apple.SwiftUI (6.5.4) <3a1e0481-99b5-3d15-a540-56402eb871a7> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x18eafc000 -        0x18eb97577 dyld (*) <3247e185-ced2-36ff-9e29-47a77c23e004> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x2776d9000 -        0x277759c63 libswift_Concurrency.dylib (*) <33017264-73ff-36d0-b876-2b45899474e2> /usr/lib/swift/libswift_Concurrency.dylib
       0x1a0640000 -        0x1a0baef3f libswiftCore.dylib (*) <7186c5c8-2a46-3f35-b27f-f7f6923f7186> /usr/lib/swift/libswiftCore.dylib
       0x19a515000 -        0x19a53cddf com.apple.audio.caulk (1.0) <42085f32-42e2-3f11-b0b4-0343137b5f72> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x18ee9d000 -        0x18eea9a47 libsystem_pthread.dylib (*) <d6494ba9-171e-39fc-b1aa-28ecf87975d1> /usr/lib/system/libsystem_pthread.dylib
       0x194a43000 -        0x194e0ca5f com.apple.CFNetwork (1.0) <45ad6442-531d-3e9a-967e-b3aa0d01f24f> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
       0x190503000 -        0x1912ec59f com.apple.Foundation (6.9) <b9a92060-f21e-3ecf-9ded-94a65c68a6f4> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 606
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)
Writable regions: Total=2.4G written=929K(0%) resident=929K(0%) swapped_out=0K(0%) unallocated=2.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
CG image                           256K       11 
ColorSync                          560K       29 
CoreAnimation                     1584K       89 
CoreGraphics                        32K        2 
CoreUI image data                 3168K       27 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             2.3G      104 
MALLOC guard page                  480K       30 
SQLite page cache                  512K        4 
STACK GUARD                       56.2M       14 
Stack                             14.9M       14 
VM_ALLOCATE                        320K       13 
__AUTH                            5370K      685 
__AUTH_CONST                      76.0M      927 
__CTF                               824        1 
__DATA                            25.2M      907 
__DATA_CONST                      26.9M      938 
__DATA_DIRTY                      2762K      337 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       619.0M        5 
__OBJC_RO                         61.4M        1 
__OBJC_RW                         2396K        1 
__TEXT                             1.0G      958 
__TPRO_CONST                       128K        2 
libnetwork                        1152K       16 
mapped file                      320.3M       45 
page table in kernel               929K        1 
shared memory                     1408K       17 
===========                     =======  ======= 
TOTAL                              4.6G     5185 



-----------
Full Report
-----------

{"app_name":"PlayCover","timestamp":"2026-03-24 19:55:16.00 +0800","app_version":"3.1.0","slice_uuid":"43c12fe4-fbbc-394d-8317-3f10f6513e55","build_version":"1428","platform":1,"bundleID":"io.playcover.PlayCover","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.6.1 (24G90)","roots_installed":0,"name":"PlayCover","incident_id":"9E08803D-4C48-451C-9ACD-9F8663142539"}
{
  "uptime" : 530000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac16,8",
  "coalitionID" : 100199,
  "osVersion" : {
    "train" : "macOS 15.6.1",
    "build" : "24G90",
    "releaseType" : "User"
  },
  "captureTime" : "2026-03-24 19:55:16.6319 +0800",
  "codeSigningMonitor" : 2,
  "incident" : "9E08803D-4C48-451C-9ACD-9F8663142539",
  "pid" : 16550,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2026-03-24 19:55:00.4896 +0800",
  "procStartAbsTime" : 12934414386910,
  "procExitAbsTime" : 12934801547481,
  "procName" : "PlayCover",
  "procPath" : "\/Applications\/PlayCover.app\/Contents\/MacOS\/PlayCover",
  "bundleInfo" : {"CFBundleShortVersionString":"3.1.0","CFBundleVersion":"1428","CFBundleIdentifier":"io.playcover.PlayCover"},
  "storeInfo" : {"deviceIdentifierForVendor":"9DE221FF-AFEB-55F3-BDC6-796993B6F720","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "io.playcover.PlayCover",
  "crashReporterKey" : "7615BF27-9E1D-8F2A-5578-3B2FC66F408D",
  "appleIntelligenceStatus" : {"state":"unavailable","reasons":["selectedLanguageDoesNotMatchSelectedSiriLanguage","regionIneligible","countryBillingIneligible","countryLocationIneligible"]},
  "codeSigningID" : "io.playcover.PlayCover",
  "codeSigningTeamID" : "792V9HMJW3",
  "codeSigningFlags" : 570520337,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "codeSigningAuxiliaryInfo" : 0,
  "instructionByteStream" : {"beforePC":"IAAg1CAAINQgACDUIAAg1CAAINQgACDUIAAg1CAAINQgACDUBN8GlA==","atPC":"IAAg1NT2QJKQ1AaUIAAg1NT2QJKN1AaUIAAg1CAAINTU9kCSidQGlA=="},
  "bootSessionUUID" : "8C7F347E-CDCA-424E-8215-A15B6616A5CA",
  "wakeTime" : 926,
  "sleepWakeUUID" : "91AC358C-AC28-4CF1-B291-62562D88D8D7",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000104dbcbd0","rawCodes":[1,4376480720],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":16550},
  "os_fault" : {"process":"PlayCover"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":606},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":10937204,"threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592,"symbolLocation":64,"symbol":"_OBJC_CLASS_RO_$_CTStewieCompressionResult"},{"value":26401163968512},{"value":0},{"value":26401163968512},{"value":2},{"value":4294967295},{"value":0},{"value":17179869184},{"value":0},{"value":2},{"value":0},{"value":0},{"value":6147},{"value":0},{"value":18446744073709551569},{"value":8554863720},{"value":0},{"value":4294967295},{"value":2},{"value":26401163968512},{"value":0},{"value":26401163968512},{"value":6090628632},{"value":8589934592,"symbolLocation":64,"symbol":"_OBJC_CLASS_RO_$_CTStewieCompressionResult"},{"value":21592279046},{"value":18446744073709550527},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6692488096},"cpsr":{"value":0},"fp":{"value":6090628480},"sp":{"value":6090628400},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692412468},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":3124,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":78752,"symbol":"mach_msg2_internal","symbolLocation":76,"imageIndex":4},{"imageOffset":38756,"symbol":"mach_msg_overwrite","symbolLocation":484,"imageIndex":4},{"imageOffset":4008,"symbol":"mach_msg","symbolLocation":24,"imageIndex":4},{"imageOffset":511164,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":505304,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":5},{"imageOffset":502424,"symbol":"CFRunLoopRunSpecific","symbolLocation":572,"imageIndex":5},{"imageOffset":799356,"symbol":"RunCurrentEventLoopInMode","symbolLocation":324,"imageIndex":6},{"imageOffset":812264,"symbol":"ReceiveNextEventCommon","symbolLocation":676,"imageIndex":6},{"imageOffset":2430084,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":76,"imageIndex":6},{"imageOffset":240180,"symbol":"_DPSNextEvent","symbolLocation":684,"imageIndex":7},{"imageOffset":10328384,"symbol":"-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":688,"imageIndex":7},{"imageOffset":187364,"symbol":"-[NSApplication run]","symbolLocation":480,"imageIndex":7},{"imageOffset":17116,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":7},{"imageOffset":297080,"symbol":"specialized runApp(_:)","symbolLocation":160,"imageIndex":8},{"imageOffset":4875864,"symbol":"runApp<A>(_:)","symbolLocation":108,"imageIndex":8},{"imageOffset":8418752,"symbol":"static App.main()","symbolLocation":224,"imageIndex":8},{"imageOffset":708816,"imageIndex":0},{"imageOffset":27544,"symbol":"start","symbolLocation":6076,"imageIndex":9}]},{"triggered":true,"id":10937231,"threadState":{"x":[{"value":105553179560456},{"value":25769803779},{"value":6689082944,"symbolLocation":0,"symbol":"dyld4::APIs::dyld_program_sdk_at_least(dyld_build_version_t)"},{"value":8554986552,"symbolLocation":584,"symbol":"vtable for dyld4::APIs"},{"value":11},{"value":2426753110},{"value":105553122088256},{"value":0},{"value":18446744065119617024},{"value":25769803779},{"value":17179869187},{"value":5440},{"value":2043},{"value":2045},{"value":2430947414},{"value":2428848215},{"value":6989655260,"symbolLocation":0,"symbol":"swift_release"},{"value":568},{"value":0},{"value":49409303784656},{"value":0},{"value":0},{"value":4611791571606948352},{"value":281474976776192},{"value":24},{"value":2},{"value":4611791571606948352},{"value":49409303784632},{"value":12}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4376480436},"cpsr":{"value":1610612736},"fp":{"value":6091188448},"sp":{"value":6091188224},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4376480720,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":232400,"imageIndex":0},{"imageOffset":239012,"imageIndex":0},{"imageOffset":241032,"imageIndex":0},{"imageOffset":242748,"imageIndex":0},{"imageOffset":243564,"imageIndex":0},{"imageOffset":115156,"imageIndex":0},{"imageOffset":54137,"imageIndex":0},{"imageOffset":213233,"imageIndex":0},{"imageOffset":54137,"imageIndex":0},{"imageOffset":415805,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":11}]},{"id":10937255,"name":"caulk.messenger.shared:17","threadState":{"x":[{"value":14},{"value":105553149517370},{"value":0},{"value":6092910698},{"value":105553149517344},{"value":25},{"value":0},{"value":0},{"value":0},{"value":4294967295},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":18446744073709551580},{"value":8554866152},{"value":0},{"value":105553154907280},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6883994824},"cpsr":{"value":2147483648},"fp":{"value":6092910464},"sp":{"value":6092910432},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692412336},"far":{"value":0}},"frames":[{"imageOffset":2992,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":7368,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":224,"imageIndex":13},{"imageOffset":7024,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":32,"imageIndex":13},{"imageOffset":6212,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":96,"imageIndex":13},{"imageOffset":27660,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":14},{"imageOffset":7040,"symbol":"thread_start","symbolLocation":8,"imageIndex":14}]},{"id":10937256,"name":"caulk.messenger.shared:high","threadState":{"x":[{"value":14},{"value":105553149517628},{"value":0},{"value":6093484140},{"value":105553149517600},{"value":27},{"value":0},{"value":0},{"value":0},{"value":4294967295},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":18446744073709551580},{"value":8554866152},{"value":0},{"value":105553154907696},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6883994824},"cpsr":{"value":2147483648},"fp":{"value":6093483904},"sp":{"value":6093483872},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692412336},"far":{"value":0}},"frames":[{"imageOffset":2992,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":7368,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":224,"imageIndex":13},{"imageOffset":7024,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":32,"imageIndex":13},{"imageOffset":6212,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":96,"imageIndex":13},{"imageOffset":27660,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":14},{"imageOffset":7040,"symbol":"thread_start","symbolLocation":8,"imageIndex":14}]},{"id":10937296,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592,"symbolLocation":64,"symbol":"_OBJC_CLASS_RO_$_CTStewieCompressionResult"},{"value":558564791812096},{"value":0},{"value":558564791812096},{"value":2},{"value":4294967295},{"value":0},{"value":17179869184},{"value":0},{"value":2},{"value":0},{"value":0},{"value":130051},{"value":0},{"value":18446744073709551569},{"value":8554863720},{"value":0},{"value":4294967295},{"value":2},{"value":558564791812096},{"value":0},{"value":558564791812096},{"value":6094053512},{"value":8589934592,"symbolLocation":64,"symbol":"_OBJC_CLASS_RO_$_CTStewieCompressionResult"},{"value":21592279046},{"value":18446744073709550527},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6692488096},"cpsr":{"value":0},"fp":{"value":6094053360},"sp":{"value":6094053280},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692412468},"far":{"value":0}},"frames":[{"imageOffset":3124,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":78752,"symbol":"mach_msg2_internal","symbolLocation":76,"imageIndex":4},{"imageOffset":38756,"symbol":"mach_msg_overwrite","symbolLocation":484,"imageIndex":4},{"imageOffset":4008,"symbol":"mach_msg","symbolLocation":24,"imageIndex":4},{"imageOffset":511164,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":505304,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":5},{"imageOffset":502424,"symbol":"CFRunLoopRunSpecific","symbolLocation":572,"imageIndex":5},{"imageOffset":1435532,"symbol":"_NSEventThread","symbolLocation":140,"imageIndex":7},{"imageOffset":27660,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":14},{"imageOffset":7040,"symbol":"thread_start","symbolLocation":8,"imageIndex":14}]},{"id":10937315,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6094630912},{"value":91143},{"value":6094094336},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6094630912},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937318,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6096351232},{"value":124419},{"value":6095814656},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6096351232},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937321,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6098071552},{"value":123907},{"value":6097534976},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6098071552},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937325,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6100365312},{"value":123395},{"value":6099828736},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6100365312},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937819,"name":"com.apple.NSURLConnectionLoader","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592,"symbolLocation":64,"symbol":"_OBJC_CLASS_RO_$_CTStewieCompressionResult"},{"value":531369058893824},{"value":0},{"value":531369058893824},{"value":2},{"value":4294967295},{"value":0},{"value":17179869184},{"value":0},{"value":2},{"value":0},{"value":0},{"value":123719},{"value":0},{"value":18446744073709551569},{"value":8554863720},{"value":0},{"value":4294967295},{"value":2},{"value":531369058893824},{"value":0},{"value":531369058893824},{"value":6091758920},{"value":8589934592,"symbolLocation":64,"symbol":"_OBJC_CLASS_RO_$_CTStewieCompressionResult"},{"value":21592279046},{"value":18446744073709550527},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6692488096},"cpsr":{"value":0},"fp":{"value":6091758768},"sp":{"value":6091758688},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692412468},"far":{"value":0}},"frames":[{"imageOffset":3124,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":78752,"symbol":"mach_msg2_internal","symbolLocation":76,"imageIndex":4},{"imageOffset":38756,"symbol":"mach_msg_overwrite","symbolLocation":484,"imageIndex":4},{"imageOffset":4008,"symbol":"mach_msg","symbolLocation":24,"imageIndex":4},{"imageOffset":511164,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":505304,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":5},{"imageOffset":502424,"symbol":"CFRunLoopRunSpecific","symbolLocation":572,"imageIndex":5},{"imageOffset":2441972,"symbol":"+[__CFN_CoreSchedulingSetRunnable _run:]","symbolLocation":416,"imageIndex":15},{"imageOffset":342952,"symbol":"__NSThread__start__","symbolLocation":732,"imageIndex":16},{"imageOffset":27660,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":14},{"imageOffset":7040,"symbol":"thread_start","symbolLocation":8,"imageIndex":14}]},{"id":10937824,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6092337152},{"value":102935},{"value":6091800576},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6092337152},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937825,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6095204352},{"value":28947},{"value":6094667776},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6095204352},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937826,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6095777792},{"value":28679},{"value":6095241216},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6095777792},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}},{"id":10937827,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":14}],"threadState":{"x":[{"value":6096924672},{"value":0},{"value":6096388096},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6096924672},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6692662124},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4376248320,
    "CFBundleShortVersionString" : "3.1.0",
    "CFBundleIdentifier" : "io.playcover.PlayCover",
    "size" : 2490368,
    "uuid" : "43c12fe4-fbbc-394d-8317-3f10f6513e55",
    "path" : "\/Applications\/PlayCover.app\/Contents\/MacOS\/PlayCover",
    "name" : "PlayCover",
    "CFBundleVersion" : "1428"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4380426240,
    "CFBundleShortVersionString" : "2.9.0",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 344064,
    "uuid" : "76717cef-e15b-3086-acee-87e1c8b99d60",
    "path" : "\/Applications\/PlayCover.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2053"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4435263488,
    "size" : 49152,
    "uuid" : "a3faee04-0f8b-3428-9497-560c97eca6fb",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4508401664,
    "CFBundleShortVersionString" : "329.2",
    "CFBundleIdentifier" : "com.apple.AGXMetalG16X",
    "size" : 7553024,
    "uuid" : "8e5557ce-84f2-3aa0-a631-94d3809e5bf0",
    "path" : "\/System\/Library\/Extensions\/AGXMetalG16X.bundle\/Contents\/MacOS\/AGXMetalG16X",
    "name" : "AGXMetalG16X",
    "CFBundleVersion" : "329.2"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6692409344,
    "size" : 243284,
    "uuid" : "6e4a96ad-04b8-3e8a-b91d-087e62306246",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6693134336,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5500928,
    "uuid" : "8d45baee-6cc0-3b89-93fd-ea1c8e15c6d7",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "3603"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6888538112,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3174368,
    "uuid" : "1a037942-11e0-3fc8-aad2-20b11e7ae1a4",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6759608320,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 21564992,
    "uuid" : "860c164c-d04c-30ff-8c6f-e672b74caf11",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2575.70.52"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7496187904,
    "CFBundleShortVersionString" : "6.5.4",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 24278048,
    "uuid" : "3a1e0481-99b5-3d15-a540-56402eb871a7",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "6.5.4"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6688849920,
    "size" : 636280,
    "uuid" : "3247e185-ced2-36ff-9e29-47a77c23e004",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 10593603584,
    "size" : 527460,
    "uuid" : "33017264-73ff-36d0-b876-2b45899474e2",
    "path" : "\/usr\/lib\/swift\/libswift_Concurrency.dylib",
    "name" : "libswift_Concurrency.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6985875456,
    "size" : 5697344,
    "uuid" : "7186c5c8-2a46-3f35-b27f-f7f6923f7186",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6883987456,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 163296,
    "uuid" : "42085f32-42e2-3f11-b0b4-0343137b5f72",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6692655104,
    "size" : 51784,
    "uuid" : "d6494ba9-171e-39fc-b1aa-28ecf87975d1",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6788755456,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.CFNetwork",
    "size" : 3971680,
    "uuid" : "45ad6442-531d-3e9a-967e-b3aa0d01f24f",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/Versions\/A\/CFNetwork",
    "name" : "CFNetwork",
    "CFBundleVersion" : "3826.600.41"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6716141568,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 14587296,
    "uuid" : "b9a92060-f21e-3ecf-9ded-94a65c68a6f4",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "3603"
  }
],
  "sharedCache" : {
  "base" : 6688014336,
  "size" : 5040898048,
  "uuid" : "4c1223e5-cace-3982-a003-6110a7a8a25c"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)\nWritable regions: Total=2.4G written=929K(0%) resident=929K(0%) swapped_out=0K(0%) unallocated=2.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nCG image                           256K       11 \nColorSync                          560K       29 \nCoreAnimation                     1584K       89 \nCoreGraphics                        32K        2 \nCoreUI image data                 3168K       27 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             2.3G      104 \nMALLOC guard page                  480K       30 \nSQLite page cache                  512K        4 \nSTACK GUARD                       56.2M       14 \nStack                             14.9M       14 \nVM_ALLOCATE                        320K       13 \n__AUTH                            5370K      685 \n__AUTH_CONST                      76.0M      927 \n__CTF                               824        1 \n__DATA                            25.2M      907 \n__DATA_CONST                      26.9M      938 \n__DATA_DIRTY                      2762K      337 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       619.0M        5 \n__OBJC_RO                         61.4M        1 \n__OBJC_RW                         2396K        1 \n__TEXT                             1.0G      958 \n__TPRO_CONST                       128K        2 \nlibnetwork                        1152K       16 \nmapped file                      320.3M       45 \npage table in kernel               929K        1 \nshared memory                     1408K       17 \n===========                     =======  ======= \nTOTAL                              4.6G     5185 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "fad5efa1a21109a414838b5d9f0b4be5233dbbf5",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6761d0c9df60af01adb250fb",
      "factorPackIds" : {

      },
      "deploymentId" : 240000009
    },
    {
      "rolloutId" : "670ea6eb7a111748a97092a4",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "68db21af3b3ace402427b77b"
      },
      "deploymentId" : 240000189
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac16,8, BootROM 11881.140.96, proc 14:10:4 processors, 48 GB, SMC 
Graphics: Apple M4 Pro, Apple M4 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Jun 24 2025 04:56:40 version 23.40.31.0.41.51.179 FWID 01-435c4c4d
IO80211_driverkit-1485.7 "IO80211_driverkit-1485.7" Jul 15 2025 20:46:41
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en7
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB Receiver
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [x] Yes my issue is written in English

### PR DESCRIPTION
**Pull request by phainia**
Fixes #2106

## Summary

Fix `String.init(data:offset:commandSize:loadCommandString:)` in `DataExtensions.swift` to stop reading at the first null byte (`0x00`) instead of consuming the entire load command region.

## Problem

When PlayCover parses Mach-O binaries during IPA installation (dylib injection / code signature removal), load command strings are read up to `commandSize`. The padding bytes after the null terminator can contain arbitrary non-UTF-8 data (e.g. `0xC5 0x0F`), causing `String(data:encoding:.utf8)` to return `nil` and crash via force-unwrap. This has been observed to cause installation failures for certain apps.

The same bug also exists in the upstream `inject` dependency — a corresponding fix has been submitted: [paradiseduo/inject#9](https://github.com/paradiseduo/inject/pull/9).

> **Note:** This PR depends on paradiseduo/inject#9 being merged first, so that PlayCover can update its `inject` dependency to include the fix on both sides.

## Fix

Read up to `commandSize` bytes, but stop at the first `0x00` null terminator before attempting UTF-8 decoding.

```diff
-        self = String(data: data[stringOffset..<(stringOffset + length)],
-                      encoding: .utf8)!.trimmingCharacters(in: .controlCharacters)
+        let rawData = data[stringOffset..<(stringOffset + length)]
+        let endIndex = rawData.firstIndex(of: 0x00) ?? rawData.endIndex
+        self = String(data: data[stringOffset..<endIndex], encoding: .utf8)!
```

### CODE REVIEW

**Comment by phainia** [comment]
The upstream dependency [paradiseduo/inject](https://github.com/paradiseduo/inject) has released [1.2.1](https://github.com/paradiseduo/inject/releases/tag/1.2.1) which includes this fix. PlayCover's existing `upToNextMajorVersion` constraint will pick it up automatically — no changes needed on this side.

Ready for review.

File: PlayCover/Utils/Extensions/DataExtensions.swift [hunk 1]
```diff
@@ -11,8 +11,9 @@ extension String {
         let loadCommandStringOffset = Int(loadCommandString.offset)
         let stringOffset = offset + loadCommandStringOffset
         let length = commandSize - loadCommandStringOffset
-        self = String(data: data[stringOffset..<(stringOffset + length)],
-                      encoding: .utf8)!.trimmingCharacters(in: .controlCharacters)
+        let rawData = data[stringOffset..<(stringOffset + length)]
+        let endIndex = rawData.firstIndex(of: 0x00) ?? rawData.endIndex
+        self = String(data: data[stringOffset..<endIndex], encoding: .utf8)!
```
Comment (TheMoonThatRises) [inline PlayCover/Utils/Extensions/DataExtensions.swift:16]: Is trimming the control characters not necessary?

Comment (moolobi) [reply PlayCover/Utils/Extensions/DataExtensions.swift:16]: No. The original `trimmingCharacters` never actually got to run in the crash case — `String(data:encoding:.utf8)` returns `nil` when it encounters non-UTF-8 padding bytes after the null terminator, and the force-unwrap `!` crashes before trimming has any chance to execute.

With this fix, we slice at the first `0x00` before decoding, so the data is already clean and trimming is unnecessary.

Comment (TheMoonThatRises) [reply PlayCover/Utils/Extensions/DataExtensions.swift:16]: Could there still be other control characters at the beginning or end of the string? Control characters are the set containing characters from Unicode General Category Cc and Cf, which could appear and may need to be removed.

Comment (moolobi) [reply PlayCover/Utils/Extensions/DataExtensions.swift:16]: `lc_str` strings are filesystem paths. A path containing Cc/Cf control characters before the null terminator would be unresolvable by dyld — the binary wouldn't load. So for any binary we actually process, the path is guaranteed to be clean before `\0`, and everything after is padding we no longer read.

**Review by TheMoonThatRises — APPROVED** [review]
