### PR TITLE
fix scroll lag

### LINKED ISSUE #1724: [Bug]: Laggy IPA Library in List view
### Describe the bug

Sutter and lag when opening IPA Library that has 50+ sources in list view. Grid view does not have the same effect, and I believe that this is because gird view uses `LazyVGrid`, which is more efficient than `VStack` or `LazyVStack`.

### Steps to reproduce

* Add an IPA source with a lot of sources (50+)
* Enter the IPA Library tab
* Switch to List view

### Expected behaviour

Works cleanly and does not stutter. This issue does not appear in grid view.

### Crash log

_No response_

### What version of PlayCover are you using?

Built from source

### What version of macOS are you using?

macOS beta (15.1)

### Issue Language

- [X] Yes my issue is written in English

### PR DESCRIPTION
**Pull request by Catta1997**
Fix (I hope) #1724

### CODE REVIEW

File: PlayCover/Utils/Cacher.swift [hunk 1]
```diff
@@ -8,16 +8,42 @@
...
+    init() {
+        // Set image cache limit.
+        ImageCache().wrappedValue.setCacheLimit(
+            countLimit: 400,
+            totalCostLimit: 4*1024*1024
+        )
+    }
+
+    func removeImageCache() {
+        imageCache.removeCache()
```
Comment (amirsaam) [inline PlayCover/Utils/Cacher.swift:32]: since you are going this path (i dunno if there are other ways) you should remove the URLCache extension in the end of this file since it was for the prev package.

File: PlayCover/Views/MenuBarView.swift [hunk 2]
```diff
@@ -110,6 +110,7 @@ struct PlayCoverViewMenuView: Commands {
             Button("menubar.clearCache") {
                 DataCache.instance.cleanAll()
                 URLCache.iconCache.removeAllCachedResponses()
```
Comment (amirsaam) [inline PlayCover/Views/MenuBarView.swift]: this should be removed too.

**Comment by amirsaam** [comment]
You need to make a way to clear prev package cache memory for the next release on launch.
e.g. you may keep the extension i mentioned in my comment and and make sure to call `URLCache.iconCache.removeAllCachedResponses()` when PlayCover launches.

**Comment by Catta1997** [comment]
> You need to make a way to clear prev package cache memory for the next release on launch. e.g. you may keep the extension i mentioned in my comment and and make sure to call `URLCache.iconCache.removeAllCachedResponses()` when PlayCover launches.

Ok, can I put this into playCoverApp -> inside an else on the if statement "!launchedBefore" ? since if the app is new I don't need to do it (but I can do it in any case, should not be a problem)

**Comment by amirsaam** [comment]
such variable cuz is new in new version will always be false on first launch

File: PlayCover/Views/App Views/StoreAppView.swift [hunk 3]
```diff
@@ -114,31 +114,48 @@ struct StoreAppConditionalView: View {
...
-                            CachedAsyncImage(url: onlineIcon, urlCache: .iconCache) { image in
-                                image
-                                    .resizable()
-                                    .aspectRatio(contentMode: .fit)
-                            } placeholder: {
-                                if let image = localIcon {
-                                    Image(nsImage: image)
+                            CachedAsyncImage(
+                                url: onlineIcon ?? "",
+                                placeholder: {_ in
```
Comment (TheMoonThatRises) [inline PlayCover/Views/App Views/StoreAppView.swift]: Missing space between `{` and `_`.

File: PlayCover.xcodeproj/project.pbxproj [hunk 4]
```diff
@@ -983,12 +983,12 @@
 				minimumVersion = 1.0.0;
 			};
 		};
-		68E48BA029570A2B00C39879 /* XCRemoteSwiftPackageReference "swiftui-cached-async-image" */ = {
+		68E48BA029570A2B00C39879 /* XCRemoteSwiftPackageReference "CachedAsyncImage" */ = {
 			isa = XCRemoteSwiftPackageReference;
-			repositoryURL = "https://github.com/lorenzofiamingo/swiftui-cached-async-image";
+			repositoryURL = "https://github.com/bullinnyc/CachedAsyncImage";
```
Comment (TheMoonThatRises) [inline PlayCover.xcodeproj/project.pbxproj:988]: Since the image cache package is being changed, can you update the README to reflect this?

File: PlayCover/Views/App Views/StoreAppView.swift [hunk 5]
```diff
@@ -114,31 +114,48 @@ struct StoreAppConditionalView: View {
...
+                                             .task(self.waitForIconLoad)
+                                    }
+                                },
+                                image: {
+                                    Image(nsImage: $0)
                                         .resizable()
                                         .aspectRatio(contentMode: .fit)
-                                } else {
+                                },
+                                error: {_, retry in
```
Comment (TheMoonThatRises) [inline PlayCover/Views/App Views/StoreAppView.swift]: Missing space between `{` and `_`.

File: PlayCover/Views/App Views/StoreAppView.swift [hunk 6]
```diff
@@ -164,34 +181,49 @@ struct StoreAppConditionalView: View {
...
-                            CachedAsyncImage(url: onlineIcon, urlCache: .iconCache) { image in
-                                image
-                                    .resizable()
-                                    .aspectRatio(contentMode: .fit)
-                            } placeholder: {
-                                if let image = localIcon {
-                                    Image(nsImage: image)
+                            CachedAsyncImage(
+                                url: onlineIcon ?? "",
+                                placeholder: {_ in
```
Comment (TheMoonThatRises) [inline PlayCover/Views/App Views/StoreAppView.swift]: Missing space between `{` and `_`.

File: PlayCover/Views/App Views/StoreAppView.swift [hunk 7]
```diff
@@ -164,34 +181,49 @@ struct StoreAppConditionalView: View {
...
+                                             .task(self.waitForIconLoad)
+                                    }
+                                },
+                                image: {
+                                    Image(nsImage: $0)
                                         .resizable()
                                         .aspectRatio(contentMode: .fit)
-                                } else {
+                                },
+                                error: {_, retry in
```
Comment (TheMoonThatRises) [inline PlayCover/Views/App Views/StoreAppView.swift]: Missing space between `{` and `_`.

File: PlayCover/Views/StoreInfoAppView.swift [hunk 8]
```diff
@@ -31,25 +31,29 @@ struct StoreInfoAppView: View {
...
-                        CachedAsyncImage(url: onlineIcon, urlCache: .iconCache) { image in
-                            image
-                                .resizable()
-                                .aspectRatio(contentMode: .fit)
-                        } placeholder: {
-                            if let image = localIcon {
-                                Image(nsImage: image)
+                        CachedAsyncImage(
+                            url: onlineIcon ?? "",
+                            placeholder: {_ in
```
Comment (TheMoonThatRises) [inline PlayCover/Views/StoreInfoAppView.swift]: Missing space between `{` and `_`.

File: PlayCover/Views/MenuBarView.swift [hunk 9]
```diff
@@ -109,7 +109,7 @@ struct PlayCoverViewMenuView: Commands {
         CommandGroup(before: .sidebar) {
             Button("menubar.clearCache") {
                 DataCache.instance.cleanAll()
-                URLCache.iconCache.removeAllCachedResponses()
+                Cacher().removeImageCache()
```
Comment (TheMoonThatRises) [inline PlayCover/Views/MenuBarView.swift]: A shared instance of `Cacher` should be called instead of an initialized instance.

File: PlayCover/Views/PlayCoverApp.swift [hunk 10]
```diff
@@ -26,6 +26,7 @@ class AppDelegate: NSObject, NSApplicationDelegate {
         if ProcessInfo.processInfo.isLowPowerModeEnabled {
             powerModal()
         }
+        URLCache.iconCache.removeAllCachedResponses()
```
Comment (TheMoonThatRises) [inline PlayCover/Views/PlayCoverApp.swift:29]: Do the icon caches need to be removed on launch?

**Review by TheMoonThatRises — CHANGES_REQUESTED** [review]

File: PlayCover/Views/PlayCoverApp.swift (hunk 10 above)
Comment (Catta1997) [reply PlayCover/Views/PlayCoverApp.swift:29]: Was asked since is the old cache method and need to be cleared since no more necessary

**Comment by amirsaam** [comment]
Since a `shared` instance of `Cacher` has been created you need to reflect this change into the codebase as in:
`PlayCover/Views/StoreInfoAppView.swift`
`PlayCover/Views/App Views/StoreAppView.swift`
`PlayCover/Views/App Views/PlayAppView.swift`

File: PlayCover/Utils/Cacher.swift [hunk 11]
```diff
@@ -8,16 +8,42 @@
 import Foundation
 import AppKit
 import DataCache
+import CachedAsyncImage
 
 class Cacher {
-
+    static let shared = Cacher()
```
Comment (amirsaam) [inline PlayCover/Utils/Cacher.swift:14]: Since a `shared` instance of `Cacher` has been created you need to reflect this change into the codebase as in:
- `PlayCover/Views/StoreInfoAppView.swift`
- `PlayCover/Views/App Views/StoreAppView.swift`
- `PlayCover/Views/App Views/PlayAppView.swift`

File: PlayCover/Utils/Cacher.swift [hunk 12]
```diff
@@ -42,14 +68,14 @@ class Cacher {
...
+            saveCachedImage(for: app.info.url, image: image)
         }
-        return cache.readImage(forKey: app.info.bundleIdentifier)
+        return getCachedImage(for: app.info.url)
     }
 
     func getLocalIcon(bundleId: String) -> NSImage? {
         if let app = AppsVM.shared.apps.first(where: { $0.info.bundleIdentifier == bundleId }) {
-            return cache.readImage(forKey: app.info.bundleIdentifier)
+            return getCachedImage(for: app.info.url)
```
Comment (amirsaam) [inline PlayCover/Utils/Cacher.swift:78]: reasoning for change from identifier to url?

Comment (Catta1997) [reply PlayCover/Utils/Cacher.swift:78]: Because on the documentation of the new `CachedAsyncImage`, to get a cached image i have to use 
```swift
private func getCachedImage(for url: URL) -> UIImage? {
        imageCache[url]
}
``` 
and `imageCache` is an array of URL and i cant change it to a String one, but maybe im doing it wrong. will check

Comment (TheMoonThatRises) [reply PlayCover/Utils/Cacher.swift:78]: Retrieving by URL is the proper method.

**Review by TheMoonThatRises — APPROVED** [review]

File: PlayCover/Utils/Cacher.swift (hunk 12 above)
Comment (amirsaam) [reply PlayCover/Utils/Cacher.swift:78]: this function is asking the installed apps for bundleids, then shows the cached image for the bundleid, if an installed app is present it will show the app icon from the installed one and not letting playcover to load from network in ipa library, plus if an app has no online icon and installed in playcover it will show the local installed app's app icon in ipa library, cachedasyncimage does anything about it i dunno but you are changing an intended behavior in playcover, please reconsider your changes.
