### PR TITLE
Various fixes

### LINKED ISSUE #526: [Bug]: Metal HUD preference not saved when closing PlayCover
### Describe the bug

Metal HUD on/off toggle under game settings is not saved, happens for every game. 

Other toggles, like Enable Discord activity, disable display sleep, etc. are saved. 

So when you enable it and then close and reopen PlayCover, it defaults back to being disabled. 

### Steps to reproduce

1. open per-app/game settings
2. enable Metal HUD 
3. close app/game
4. close PlayCover
5. open PlayCover
6. check the toggle 

### Expected behaviour

The preference getting preserved on app close like all other options/toggles. 

### Crash log

```shell
N/A
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
- Save Metal HUD state (closes #526)
- Add PlayChain to the uninstaller
- Sort libraries alphabetically

### CODE REVIEW

File: PlayCover/ViewModel/AppsVM.swift [hunk 1]
```diff
@@ -62,6 +62,7 @@ class AppsVM: ObservableObject {
             filteredApps = newApps.filter({ $0.searchText.contains(uif.searchText.lowercased()) })
         }
 
+        filteredApps.sort(by: { $0.name < $1.name })
```
Comment (Depal1) [inline PlayCover/ViewModel/AppsVM.swift]: Sorting should be case insensitive.

File: PlayCover/Views/Uninstaller.swift [hunk 2]
```diff
@@ -53,7 +54,8 @@ class Uninstaller {
                 ("removeAppEntitlements", NSLocalizedString("preferences.toggle.removeEntitlements", comment: "")),
                 ("removeAppSettings", NSLocalizedString("preferences.toggle.removeSetting", comment: "")),
                 ("removeAppKeymap", NSLocalizedString("preferences.toggle.removeKeymap", comment: "")),
-                ("clearAppData", NSLocalizedString("preferences.toggle.clearAppData", comment: ""))
+                ("clearAppData", NSLocalizedString("preferences.toggle.clearAppData", comment: "")),
+                ("removePlayChain", NSLocalizedString("preferences.toggle.removePlayChain", comment: ""))
```
Comment (Depal1) [inline PlayCover/Views/Uninstaller.swift]: The disposition of the items is not being kept.
Screenshot 2023-01-31 at 20 29 28
Screenshot 2023-01-31 at 20 29 15

**Review by Depal1 — CHANGES_REQUESTED** [review]

File: PlayCover/Views/Settings/UninstallSettings.swift [hunk 3]
```diff
@@ -14,6 +14,7 @@ class UninstallPreferences: NSObject, ObservableObject {
     @objc @AppStorage("RemoveAppKeymapUninstall") var removeAppKeymap = false
     @objc @AppStorage("RemoveAppSettingUninstall") var removeAppSettings = false
     @objc @AppStorage("RemoveAppEntitlementsUninstall") var removeAppEntitlements = false
+    @objc @AppStorage("RemovePlayChain") var removePlayChain = false
```
Comment (TheMoonThatRises) [inline PlayCover/Views/Settings/UninstallSettings.swift]: The key for the App Storage should have the `Uninstall` prefix to maintain the uninstall setting naming convention.

**Review by TheMoonThatRises — APPROVED** [review]

**Review by Depal1 — APPROVED** [review]
