### PR TITLE
Code Cleanup + Styling Fixes + Image Cache

### LINKED ISSUE #362: [Bug]: Scrolling down in App Library with grid list view crashes the app [16+ apps]
### Describe the bug

Scrolling down in App Library with grid list view crashes the app when it has at least 16 apps installed, provided the window has not been resized.

This issue does not seem to happen in IPA Library, list view, or when the window has been resized.

### Steps to reproduce

*Setup*:
1. Install at least 16 apps, so it is possible to scroll down in grid list view with the default window size.

*Reproduce*:
1. Open PlayCover.
2. The app opens in grid list view by default. **Don't resize the window**.
3. Scroll down.

This issue can also present itself if the window is resized, it is unselected, and then selected back.

### Expected behaviour

PlayCover shouldn't crash in this scenario.

### Crash log

<details>
<summary>Crash log</summary>

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               PlayCover [1219]
Path:                  /Applications/PlayCover.app/Contents/MacOS/PlayCover
Identifier:            io.playcover.PlayCover
Version:               2.0.0 (65)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-02 13:41:24.3971 -0600
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        987ECCBB-6299-16DB-29ED-4D886C07241F

Sleep/Wake UUID:       2CCE42E2-D0C6-471D-B888-19915F18EB54

Time Awake Since Boot: 10000 seconds
Time Since Wake:       316 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000011e151fd8
Exception Codes:       0x0000000000000001, 0x000000011e151fd8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1219]

VM Region Info: 0x11e151fd8 is not in any region.  Bytes after previous region: 10428377  Bytes before following region: 1941544
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      CoreAnimation               11d75c000-11d760000    [   16K] r--/r-- SM=PRV  
--->  GAP OF 0xbcc000 BYTES
      CoreAnimation               11e32c000-11e330000    [   16K] r--/r-- SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   CoreUI                        	       0x1a11353f8 __csiCopyImageTextureDataWithOptions + 136
1   CoreUI                        	       0x1a11353f4 __csiCopyImageTextureDataWithOptions + 132
2   QuartzCore                    	       0x1a0d9f408 CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double) + 1248
3   QuartzCore                    	       0x1a0d9eed0 CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double) + 24
4   QuartzCore                    	       0x1a0d9ebc8 CA::Layer::prepare_commit(CA::Transaction*) + 500
5   QuartzCore                    	       0x1a0ee663c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 480
6   QuartzCore                    	       0x1a0d7b4cc CA::Transaction::commit() + 704
7   AppKit                        	       0x19cbd169c __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 304
8   AppKit                        	       0x19d336758 ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
9   CoreFoundation                	       0x199f001a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
10  CoreFoundation                	       0x199effff4 __CFRunLoopDoObservers + 592
11  CoreFoundation                	       0x199eff528 __CFRunLoopRun + 772
12  CoreFoundation                	       0x199efea84 CFRunLoopRunSpecific + 600
13  HIToolbox                     	       0x1a2b3e338 RunCurrentEventLoopInMode + 292
14  HIToolbox                     	       0x1a2b3dfc4 ReceiveNextEventCommon + 324
15  HIToolbox                     	       0x1a2b3de68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
16  AppKit                        	       0x19ca6651c _DPSNextEvent + 860
17  AppKit                        	       0x19ca64e14 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
18  AppKit                        	       0x19ca56fe0 -[NSApplication run] + 596
19  AppKit                        	       0x19ca286fc NSApplicationMain + 1132
20  SwiftUI                       	       0x1bf47ee98 specialized runApp(_:) + 148
21  SwiftUI                       	       0x1c000d588 runApp<A>(_:) + 260
22  SwiftUI                       	       0x1bfa8326c static App.main() + 128
23  PlayCover                     	       0x104126cc0 0x104120000 + 27840
24  dyld                          	       0x10442908c start + 520

Thread 1:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x199df68ec semaphore_wait_trap + 8
1   caulk                         	       0x1a28a9a2c caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1a288d7ac caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1a288d3cc void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x199e3426c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x199e2f08c thread_start + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x199df68b0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x199df6d20 mach_msg + 76
2   CoreFoundation                	       0x199f01210 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x199eff6c0 __CFRunLoopRun + 1180
4   CoreFoundation                	       0x199efea84 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x19cbd3100 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x199e3426c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x199e2f08c thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x199e2f078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x199e2f078 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x199e2f078 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x199e2f078 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000004   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000109800000   x6: 0x000000016bcdc5f8   x7: 0x00000001a0db97fc
    x8: 0x000000011e151fd0   x9: 0x0000000000000006  x10: 0x9fd621ff40d61fff  x11: 0x00000000000000ff
   x12: 0x000000000000006b  x13: 0x000000012b0f3ca0  x14: 0x0000000000fb0139  x15: 0x00000001f29187b8
   x16: 0x0000000199df65e4  x17: 0x00000001f43b8bb8  x18: 0x0000000000000000  x19: 0x00006000009ac870
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x00006000015ceb80  x23: 0x0000000000000000
   x24: 0x000000002b500009  x25: 0x000000013c0cfdc0  x26: 0x00000001f01d2000  x27: 0x00000001f01d1000
   x28: 0x0000000000000000   fp: 0x000000016bcdc680   lr: 0x39540001a11353f4
    sp: 0x000000016bcdc650   pc: 0x00000001a11353f8 cpsr: 0x60001000
   far: 0x000000011e151fd8  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x1a10f5000 -        0x1a1233fff com.apple.coreui (2.1) <4c64f340-d315-3639-ae9e-9c3008f1c5fa> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
       0x1a0d79000 -        0x1a10a4fff com.apple.QuartzCore (1.11) <239ccbf7-85b5-3a4c-bf04-d50cf65feaea> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
       0x19ca25000 -        0x19d8ddfff com.apple.AppKit (6.9) <5e432f87-5b58-391a-a542-fa2d909dd210> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x199e7c000 -        0x19a3c2fff com.apple.CoreFoundation (6.9) <fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a2b0c000 -        0x1a2e3ffff com.apple.HIToolbox (2.1.1) <aaf900bd-bfb6-3af0-a8d3-e24bbe1d57f5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1bf3ea000 -        0x1c0439fff com.apple.SwiftUI (3.5.2) <98813c4b-96b1-3e84-adec-0b77331f3c99> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x104120000 -        0x10423bfff io.playcover.PlayCover (2.0.0) <a0e0f821-8e86-37c5-800b-bec3583083a0> /Applications/PlayCover.app/Contents/MacOS/PlayCover
       0x104424000 -        0x104483fff dyld (*) <38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6> /usr/lib/dyld
       0x199df5000 -        0x199e2cfff libsystem_kernel.dylib (*) <a9d87740-9c1d-3468-bf60-720a8d713cba> /usr/lib/system/libsystem_kernel.dylib
       0x1a288b000 -        0x1a28b1fff com.apple.audio.caulk (1.0) <fbaaa1ec-abbe-3c0d-a491-0dc66ee9d8ce> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x199e2d000 -        0x199e39fff libsystem_pthread.dylib (*) <63c4eef9-69a5-38b1-996e-8d31b66a051d> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               640K        5 
Activity Tracing                   256K        1 
CG backing stores                 1536K        8 
CG image                           336K       13 
ColorSync                          624K       27 
CoreAnimation                     1056K       59 
CoreGraphics                        64K        4 
CoreUI image data                  592K       11 
Foundation                          16K        1 
Image IO                           896K        8 
Kernel Alloc Once                   32K        1 
MALLOC                           323.5M       69 
MALLOC guard page                  288K       15 
MALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  128K        2 
STACK GUARD                       56.1M        7 
Stack                             11.2M        7 
VM_ALLOCATE                       3328K       17 
__AUTH                            2445K      256 
__AUTH_CONST                      19.0M      443 
__CTF                               756        1 
__DATA                            12.1M      433 
__DATA_CONST                      15.7M      449 
__DATA_DIRTY                      1557K      172 
__FONT_DATA                          4K        1 
__LINKEDIT                       578.0M        5 
__OBJC_CONST                      2644K      214 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           453.4M      466 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                         640K       16 
mapped file                      171.0M       27 
shared memory                     2960K       17 
===========                     =======  ======= 
TOTAL                              3.3G     2770 
TOTAL, minus reserved VM space     1.7G     2770 



-----------
Full Report
-----------

{"app_name":"PlayCover","timestamp":"2022-10-02 13:41:26.00 -0600","app_version":"2.0.0","slice_uuid":"a0e0f821-8e86-37c5-800b-bec3583083a0","build_version":"65","platform":1,"bundleID":"io.playcover.PlayCover","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"A33267E0-D3E8-4B48-859B-525B4C60B9A7","name":"PlayCover"}
{
  "uptime" : 10000,
  "procLaunch" : "2022-10-02 11:33:20.6728 -0600",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac13,1",
  "procStartAbsTime" : 107894472696,
  "coalitionID" : 1222,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-02 13:41:24.3971 -0600",
  "incident" : "A33267E0-D3E8-4B48-859B-525B4C60B9A7",
  "bug_type" : "309",
  "pid" : 1219,
  "procExitAbsTime" : 255313514856,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "PlayCover",
  "procPath" : "\/Applications\/PlayCover.app\/Contents\/MacOS\/PlayCover",
  "bundleInfo" : {"CFBundleShortVersionString":"2.0.0","CFBundleVersion":"65","CFBundleIdentifier":"io.playcover.PlayCover"},
  "storeInfo" : {"deviceIdentifierForVendor":"F6EF589F-A58F-53EA-BEFC-D3E643DC5972","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "io.playcover.PlayCover",
  "crashReporterKey" : "987ECCBB-6299-16DB-29ED-4D886C07241F",
  "wakeTime" : 316,
  "sleepWakeUUID" : "2CCE42E2-D0C6-471D-B888-19915F18EB54",
  "sip" : "enabled",
  "vmRegionInfo" : "0x11e151fd8 is not in any region.  Bytes after previous region: 10428377  Bytes before following region: 1941544\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      CoreAnimation               11d75c000-11d760000    [   16K] r--\/r-- SM=PRV  \n--->  GAP OF 0xbcc000 BYTES\n      CoreAnimation               11e32c000-11e330000    [   16K] r--\/r-- SM=PRV  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x000000011e151fd8","rawCodes":[1,4799668184],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x000000011e151fd8"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":1219},
  "vmregioninfo" : "0x11e151fd8 is not in any region.  Bytes after previous region: 10428377  Bytes before following region: 1941544\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      CoreAnimation               11d75c000-11d760000    [   16K] r--\/r-- SM=PRV  \n--->  GAP OF 0xbcc000 BYTES\n      CoreAnimation               11e32c000-11e330000    [   16K] r--\/r-- SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":43281,"threadState":{"x":[{"value":0},{"value":4},{"value":0},{"value":0},{"value":0},{"value":4454350848},{"value":6103614968},{"value":6993713148,"symbolLocation":0,"symbol":"CA::Render::(anonymous namespace)::provider_free(void const*, void*)"},{"value":4799668176},{"value":6},{"value":11517430477234774015},{"value":255},{"value":107},{"value":5017386144},{"value":16449849},{"value":8364591032,"symbolLocation":0,"symbol":"OBJC_CLASS_$__TtC7SwiftUI10ImageLayer"},{"value":6876521956,"symbolLocation":0,"symbol":"kdebug_trace"},{"value":8392510392},{"value":0},{"value":105553126410352},{"value":0},{"value":0},{"value":105553139133312},{"value":0},{"value":726663177},{"value":5302451648},{"value":8323407872,"symbolLocation":8,"symbol":"CA::OGL::flip_transition_init()::unaligned_flip"},{"value":8323403776},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4130926765202953204},"cpsr":{"value":1610616832},"fp":{"value":6103615104},"sp":{"value":6103615056},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6997365752,"matchesCrashFrame":1},"far":{"value":4799668184}},"queue":"com.apple.main-thread","frames":[{"imageOffset":263160,"symbol":"__csiCopyImageTextureDataWithOptions","symbolLocation":136,"imageIndex":0},{"imageOffset":263156,"symbol":"__csiCopyImageTextureDataWithOptions","symbolLocation":132,"imageIndex":0},{"imageOffset":156680,"symbol":"CA::Render::copy_image(CGImage*, CGColorSpace*, unsigned int, double, double)","symbolLocation":1248,"imageIndex":1},{"imageOffset":155344,"symbol":"CA::Render::prepare_image(CGImage*, CGColorSpace*, unsigned int, double)","symbolLocation":24,"imageIndex":1},{"imageOffset":154568,"symbol":"CA::Layer::prepare_commit(CA::Transaction*)","symbolLocation":500,"imageIndex":1},{"imageOffset":1496636,"symbol":"CA::Context::commit_transaction(CA::Transaction*, double, double*)","symbolLocation":480,"imageIndex":1},{"imageOffset":9420,"symbol":"CA::Transaction::commit()","symbolLocation":704,"imageIndex":1},{"imageOffset":1754780,"symbol":"__62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke","symbolLocation":304,"imageIndex":2},{"imageOffset":9508696,"symbol":"___NSRunLoopObserverCreateWithHandler_block_invoke","symbolLocation":64,"imageIndex":2},{"imageOffset":541092,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__","symbolLocation":36,"imageIndex":3},{"imageOffset":540660,"symbol":"__CFRunLoopDoObservers","symbolLocation":592,"imageIndex":3},{"imageOffset":537896,"symbol":"__CFRunLoopRun","symbolLocation":772,"imageIndex":3},{"imageOffset":535172,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":3},{"imageOffset":205624,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":4},{"imageOffset":204740,"symbol":"ReceiveNextEventCommon","symbolLocation":324,"imageIndex":4},{"imageOffset":204392,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":4},{"imageOffset":267548,"symbol":"_DPSNextEvent","symbolLocation":860,"imageIndex":2},{"imageOffset":261652,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1328,"imageIndex":2},{"imageOffset":204768,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":2},{"imageOffset":14076,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":2},{"imageOffset":609944,"symbol":"specialized runApp(_:)","symbolLocation":148,"imageIndex":5},{"imageOffset":12727688,"symbol":"runApp<A>(_:)","symbolLocation":260,"imageIndex":5},{"imageOffset":6918764,"symbol":"static App.main()","symbolLocation":128,"imageIndex":5},{"imageOffset":27840,"imageIndex":6},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":7}]},{"id":43335,"name":"AMCP Logging Spool","frames":[{"imageOffset":6380,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":125484,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":9},{"imageOffset":10156,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":9},{"imageOffset":9164,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":9},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":43358,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6320,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":7456,"symbol":"mach_msg","symbolLocation":76,"imageIndex":8},{"imageOffset":545296,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":3},{"imageOffset":538304,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":3},{"imageOffset":535172,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":3},{"imageOffset":1761536,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":2},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":84379,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":84742,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":84743,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":84783,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6997102592,
    "CFBundleShortVersionString" : "2.1",
    "CFBundleIdentifier" : "com.apple.coreui",
    "size" : 1306624,
    "uuid" : "4c64f340-d315-3639-ae9e-9c3008f1c5fa",
    "path" : "\/System\/Library\/PrivateFrameworks\/CoreUI.framework\/Versions\/A\/CoreUI",
    "name" : "CoreUI",
    "CFBundleVersion" : "738.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6993448960,
    "CFBundleShortVersionString" : "1.11",
    "CFBundleIdentifier" : "com.apple.QuartzCore",
    "size" : 3325952,
    "uuid" : "239ccbf7-85b5-3a4c-bf04-d50cf65feaea",
    "path" : "\/System\/Library\/Frameworks\/QuartzCore.framework\/Versions\/A\/QuartzCore",
    "name" : "QuartzCore",
    "CFBundleVersion" : "964.35"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6922850304,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "5e432f87-5b58-391a-a542-fa2d909dd210",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6877069312,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "fc3c193d-0cdb-3569-9f0e-bd2507ca1dbb",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7024459776,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "aaf900bd-bfb6-3af0-a8d3-e24bbe1d57f5",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7503519744,
    "CFBundleShortVersionString" : "3.5.2",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 17104896,
    "uuid" : "98813c4b-96b1-3e84-adec-0b77331f3c99",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "3.5.2"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4363255808,
    "CFBundleShortVersionString" : "2.0.0",
    "CFBundleIdentifier" : "io.playcover.PlayCover",
    "size" : 1163264,
    "uuid" : "a0e0f821-8e86-37c5-800b-bec3583083a0",
    "path" : "\/Applications\/PlayCover.app\/Contents\/MacOS\/PlayCover",
    "name" : "PlayCover",
    "CFBundleVersion" : "65"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4366417920,
    "size" : 393216,
    "uuid" : "38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6876516352,
    "size" : 229376,
    "uuid" : "a9d87740-9c1d-3468-bf60-720a8d713cba",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7021834240,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 159744,
    "uuid" : "fbaaa1ec-abbe-3c0d-a491-0dc66ee9d8ce",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6876745728,
    "size" : 53248,
    "uuid" : "63c4eef9-69a5-38b1-996e-8d31b66a051d",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6873448448,
  "size" : 3144744960,
  "uuid" : "049b583e-d4dc-3b2b-88da-e52d6e18313d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.9G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.9G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               640K        5 \nActivity Tracing                   256K        1 \nCG backing stores                 1536K        8 \nCG image                           336K       13 \nColorSync                          624K       27 \nCoreAnimation                     1056K       59 \nCoreGraphics                        64K        4 \nCoreUI image data                  592K       11 \nFoundation                          16K        1 \nImage IO                           896K        8 \nKernel Alloc Once                   32K        1 \nMALLOC                           323.5M       69 \nMALLOC guard page                  288K       15 \nMALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  128K        2 \nSTACK GUARD                       56.1M        7 \nStack                             11.2M        7 \nVM_ALLOCATE                       3328K       17 \n__AUTH                            2445K      256 \n__AUTH_CONST                      19.0M      443 \n__CTF                               756        1 \n__DATA                            12.1M      433 \n__DATA_CONST                      15.7M      449 \n__DATA_DIRTY                      1557K      172 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       578.0M        5 \n__OBJC_CONST                      2644K      214 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           453.4M      466 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                         640K       16 \nmapped file                      171.0M       27 \nshared memory                     2960K       17 \n===========                     =======  ======= \nTOTAL                              3.3G     2770 \nTOTAL, minus reserved VM space     1.7G     2770 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "6216ae152a40e71046e16225"
      },
      "deploymentId" : 240000016
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "5b729754-3882-4560-826f-9c0bc27d77c6",
      "experimentId" : "6192fb082171a2330e561df0",
      "deploymentId" : 400000035
    }
  ]
}
}

Model: Mac13,1, BootROM 7459.141.1, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: LG FHD, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Display: LG FULL HD, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Apr  6 2022 06:12:09 version 20.90.45.0.8.7.118 FWID 01-13a89935
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: USB C Video Adaptor
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB  AUDIO
USB Device: Twin USB Joystick
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB2 Hub
USB Device: Hub in Apple Extended USB Keyboard
USB Device: Apple Extended USB Keyboard
USB Device: USB3 Gen2 Hub
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.
```
</details>

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
This PR fixes #362 
This also fixes issues where Duolingo, Infinity Blade, and Netflix would show with the wrong/no icon

### CODE REVIEW

File: PlayCover/Utils/ImageCache.swift [hunk 1]
```diff
@@ -0,0 +1,160 @@
+//
+//  ImageCache.swift
+//  PlayCover
+//
+//  Created by Isaac Marovitz on 17/10/2022.
+//
+
+import Foundation
+
+class ImageCache {
```
Comment (Candygoblen123) [inline PlayCover/Utils/ImageCache.swift:10]: There isn't much of a reason to implement our own image cache when implementations like https://github.com/lorenzofiamingo/swiftui-cached-async-image already exist.

File: PlayCover/Utils/ImageCache.swift [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+    static let cacheFolder = PlayTools.playCoverContainer.appendingPathComponent("Image Cache")
```
Comment (Candygoblen123) [inline PlayCover/Utils/ImageCache.swift]: Instead of chucking everything into a folder, we should use the system cache.

File: PlayCover/Utils/ImageCache.swift [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+                    }
+                }
+            }
+        } catch {
+            Log.shared.error(error)
+        }
+
+        if bestResImage != nil {
+            print("Found icon for \(bundleID) in bundle")
+            return saveImageToCache(image: bestResImage!, bundleID: bundleID)
```
Comment (Candygoblen123) [inline PlayCover/Utils/ImageCache.swift]: Why are we caching images that already exist on disk?

**Review by Candygoblen123 — DISMISSED** [review]

**Review by Depal1 — APPROVED** [review]
